version: "3"

services:
  climsoft_api:
    image: climsoft_api:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: climsoft_api
    ports:
      - "5080:5000"
    environment:
      - CLIMSOFT_SECRET_KEY=*93uuasdjfojalsdf832or;aljfpo2upo
      - CLIMSOFT_DATABASE_URI=mysql+mysqldb://root:password@mariadb:3306/climsoft
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - ./src/climsoft_api:/app/climsoft_api
      - ./climsoft_uploads:/climsoft_uploads
    networks:
      - climsoft_api_dev_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`$HOST_FQDN`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
    command:
      [
        "uvicorn",
        "climsoft_api.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--reload",
        "--use-colors",
      ]

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    container_name: mariadb
    ports:
      - "23306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=climsoft
    networks:
      - climsoft_api_dev_network
    volumes:
      - climsoftdb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10
      interval: 10s

  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/traefik/traefik.toml:/etc/traefik/traefik.toml"

volumes:
  climsoftdb_data:

networks:
  climsoft_api_dev_network:
