name: Run tests

on:
  push:

jobs:
  test-job:
    runs-on: ubuntu-latest
    container: python:3.8

    services:
      mariadb:
        image: mariadb:10.1
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: climsoft
        ports:
          - "3306:3306"
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip install .
      - name: Run tests
        run: |
          mv deployment.yml deployment_bk.yml
          export CLIMSOFT_AUTH_ENABLED=false
          pytest tests/integration
